/* Built-in exercise catalog. Primary muscle is used for planning and volume views. */
(function(root){
  "use strict";
  root.ProgressionExerciseLibrary=[
    {name:"Barbell bench press",cat:"compound",muscle:"Chest",equipment:"barbell"},{name:"Incline barbell bench press",cat:"compound",muscle:"Chest",equipment:"barbell"},{name:"Dumbbell bench press",cat:"compound",muscle:"Chest",equipment:"dumbbells"},{name:"Incline dumbbell press",cat:"compound",muscle:"Chest",equipment:"dumbbells"},{name:"Push-up",cat:"compound",muscle:"Chest",equipment:"bodyweight"},{name:"Machine chest press",cat:"compound",muscle:"Chest",equipment:"machine"},{name:"Cable chest fly",cat:"isolation",muscle:"Chest",equipment:"cable"},{name:"Dumbbell fly",cat:"isolation",muscle:"Chest",equipment:"dumbbells"},
    {name:"Barbell row",cat:"compound",muscle:"Back",equipment:"barbell"},{name:"Dumbbell row",cat:"compound",muscle:"Back",equipment:"dumbbells"},{name:"Seated cable row",cat:"compound",muscle:"Back",equipment:"cable"},{name:"Machine row",cat:"compound",muscle:"Back",equipment:"machine"},{name:"Lat pulldown",cat:"compound",muscle:"Back",equipment:"cable"},{name:"Assisted pull-up",cat:"compound",muscle:"Back",equipment:"machine"},{name:"Pull-up",cat:"compound",muscle:"Back",equipment:"bodyweight"},{name:"Straight-arm pulldown",cat:"isolation",muscle:"Back",equipment:"cable"},
    {name:"Overhead barbell press",cat:"compound",muscle:"Shoulders",equipment:"barbell"},{name:"Dumbbell shoulder press",cat:"compound",muscle:"Shoulders",equipment:"dumbbells"},{name:"Machine shoulder press",cat:"compound",muscle:"Shoulders",equipment:"machine"},{name:"Dumbbell lateral raise",cat:"isolation",muscle:"Shoulders",equipment:"dumbbells"},{name:"Cable lateral raise",cat:"isolation",muscle:"Shoulders",equipment:"cable"},{name:"Face pull",cat:"isolation",muscle:"Shoulders",equipment:"cable"},{name:"Rear-delt fly",cat:"isolation",muscle:"Shoulders",equipment:"dumbbells"},
    {name:"Barbell back squat",cat:"leg",muscle:"Quads",equipment:"barbell"},{name:"Front squat",cat:"leg",muscle:"Quads",equipment:"barbell"},{name:"Goblet squat",cat:"leg",muscle:"Quads",equipment:"dumbbells"},{name:"Leg press",cat:"leg",muscle:"Quads",equipment:"machine"},{name:"Leg extension",cat:"leg",muscle:"Quads",equipment:"machine"},{name:"Split squat",cat:"leg",muscle:"Quads",equipment:"dumbbells"},{name:"Step-up",cat:"leg",muscle:"Quads",equipment:"dumbbells"},
    {name:"Romanian deadlift",cat:"leg",muscle:"Hamstrings",equipment:"barbell"},{name:"Dumbbell Romanian deadlift",cat:"leg",muscle:"Hamstrings",equipment:"dumbbells"},{name:"Seated leg curl",cat:"leg",muscle:"Hamstrings",equipment:"machine"},{name:"Lying leg curl",cat:"leg",muscle:"Hamstrings",equipment:"machine"},{name:"Nordic curl",cat:"leg",muscle:"Hamstrings",equipment:"bodyweight"},{name:"Hip thrust",cat:"leg",muscle:"Glutes",equipment:"barbell"},{name:"Glute bridge",cat:"leg",muscle:"Glutes",equipment:"bodyweight"},{name:"Cable pull-through",cat:"leg",muscle:"Glutes",equipment:"cable"},
    {name:"Barbell curl",cat:"isolation",muscle:"Biceps",equipment:"barbell"},{name:"Dumbbell curl",cat:"isolation",muscle:"Biceps",equipment:"dumbbells"},{name:"Hammer curl",cat:"isolation",muscle:"Biceps",equipment:"dumbbells"},{name:"Cable curl",cat:"isolation",muscle:"Biceps",equipment:"cable"},{name:"Triceps pushdown",cat:"isolation",muscle:"Triceps",equipment:"cable"},{name:"Overhead triceps extension",cat:"isolation",muscle:"Triceps",equipment:"dumbbells"},{name:"Dips",cat:"compound",muscle:"Triceps",equipment:"bodyweight"},
    {name:"Standing calf raise",cat:"leg",muscle:"Calves",equipment:"machine"},{name:"Single-leg calf raise",cat:"leg",muscle:"Calves",equipment:"bodyweight"},{name:"Cable crunch",cat:"isolation",muscle:"Core",equipment:"cable"},{name:"Dead bug",cat:"isolation",muscle:"Core",equipment:"bodyweight"},{name:"Plank",cat:"isolation",muscle:"Core",equipment:"bodyweight"},{name:"Pallof press",cat:"isolation",muscle:"Core",equipment:"cable"}
  ];
})(typeof window!=="undefined"?window:globalThis);
